name: myapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: 1.14.11
  device_info: 0.2.1
  intl: 0.15.7
  connectivity: 0.3.2
  string_scanner: 1.0.4
  url_launcher: 4.0.1
  cupertino_icons: 0.1.2
  video_player: 0.7.2
  charcode: 1.1.2
  meta: 1.1.6
  path: 1.6.2
  source_span: 1.4.1
  typed_data: 1.1.6
  vector_math: 2.0.8

  # app中的所有资源文件存储在该依赖包中 https://github.com/zhanglingsi/gallery-assets-china.git
  # flutter_myapp_assets: 0.1.7
  flutter_myapp_assets:
    git:
      url: https://github.com/zhanglingsi/gallery-assets-china
      ref: 7debaa75fdf53e7935453b7f3da7eabc29f442d4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_goldens:
    sdk: flutter
  test: 1.5.1

  analyzer: 0.33.3
  args: 1.5.1
  async: 2.0.8
  boolean_selector: 1.0.4
  convert: 2.0.2
  crypto: 2.0.6
  csslib: 0.14.6
  file: 5.0.6
  front_end: 0.1.6+3
  glob: 1.1.7
  html: 0.13.3+3
  http: 0.12.0
  http_multi_server: 2.0.5
  http_parser: 3.1.3
  io: 0.3.3
  js: 0.6.1+1
  json_rpc_2: 2.0.9
  kernel: 0.3.6+3
  logging: 0.11.3+2
  matcher: 0.12.3+1
  mime: 0.9.6+2
  multi_server_socket: 1.0.2
  node_preamble: 1.4.4
  package_config: 1.0.5
  package_resolver: 1.0.6
  platform: 2.2.0
  plugin: 0.2.0+3
  pool: 1.3.6
  process: 3.0.9
  pub_semver: 1.4.2
  quiver: 2.0.1
  shelf: 0.7.3+3
  shelf_packages_handler: 1.0.4
  shelf_static: 0.2.8
  shelf_web_socket: 0.2.2+4
  source_map_stack_trace: 1.1.5
  source_maps: 0.10.8
  stack_trace: 1.9.3
  stream_channel: 1.6.8
  term_glyph: 1.0.1
  test_api: 0.2.1
  test_core: 0.2.0
  utf: 0.9.0+5
  vm_service_client: 0.2.6
  watcher: 0.9.7+10
  web_socket_channel: 1.0.9
  yaml: 2.1.15

flutter:
  uses-material-design: true
  assets:
    - lib/myapp/example_code.dart
    - packages/flutter_myapp_assets/videos/bee.mp4
    - packages/flutter_myapp_assets/videos/butterfly.mp4
    - packages/flutter_myapp_assets/animated_flutter_lgtm.gif
    - packages/flutter_myapp_assets/animated_flutter_stickers.webp

  fonts:
    # - family: Raleway
    #   fonts:
    #     - asset: packages/flutter_myapp_assets/fonts/raleway/Raleway-Regular.ttf
    #     - asset: packages/flutter_myapp_assets/fonts/raleway/Raleway-Medium.ttf
    #       weight: 500
    #     - asset: packages/flutter_myapp_assets/fonts/raleway/Raleway-SemiBold.ttf
    #       weight: 600
    # - family: AbrilFatface
    #   fonts:
    #     - asset: packages/flutter_myapp_assets/fonts/abrilfatface/AbrilFatface-Regular.ttf
    - family: MyAppIcons
      fonts:
        - asset: packages/flutter_myapp_assets/fonts/GalleryIcons.ttf
    - family: GoogleSans
      fonts:
        - asset: packages/flutter_myapp_assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/flutter_myapp_assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: packages/flutter_myapp_assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/flutter_myapp_assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/flutter_myapp_assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: packages/flutter_myapp_assets/fonts/GoogleSans-Regular.ttf
          weight: 400
    - family: GoogleSansDisplay
      fonts:
        - asset: packages/flutter_myapp_assets/fonts/GoogleSansDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/flutter_myapp_assets/fonts/GoogleSansDisplay-Bold.ttf
          weight: 700
        - asset: packages/flutter_myapp_assets/fonts/GoogleSansDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/flutter_myapp_assets/fonts/GoogleSansDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: packages/flutter_myapp_assets/fonts/GoogleSansDisplay-Medium.ttf
          weight: 500
        - asset: packages/flutter_myapp_assets/fonts/GoogleSansDisplay-Regular.ttf
          weight: 400
